version: "3.8"

services:
  taxi-server:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    container_name: taxi-server
    depends_on:
      - taxi-redis
      - taxi-database # new
    environment:
      - PGDATABASE=taxi # new
      - PGUSER=taxi # new
      - PGPASSWORD=taxi # new
      - PGHOST=taxi-database # new
      - REDIS_URL=redis://taxi-redis:6379/0
    ports:
      - 8000:8000

  taxi-redis:
    container_name: taxi-redis
    image: redis:6-alpine

  # new
  taxi-database:
    container_name: taxi-database
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=taxi
      - POSTGRES_PASSWORD=taxi
    expose:
      - 5432
    volumes:
      - taxi-database:/var/lib/postgresql/data

# new
volumes:
  taxi-database:
